# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Action Build on Ubuntu Machines
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5

    - name: Install Ninja on Linux
      run: sudo apt-get install ninja-build
  
    - name: Install Python Packages
      run: |
          sudo pip3 install lit numpy
          sudo pip3 install pybind11

    - uses: actions/checkout@v4

    - name: LLVM Configure CMake
      run: | 
          cd ${{github.workspace}}/third_party;
          rm -rf llvm-project;
          git clone --depth 10 --single-branch --branch ln-specific https://github.com/CYCLE-Lab/llvm-project.git;
          cd llvm-project;
          cmake -B build -G Ninja llvm \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_TARGETS_TO_BUILD="host" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
            -DLLVM_ENABLE_LIBEDIT=OFF ;
          cd "${{github.workspace}}"

    - name: LLVM Build
      run: cd "${{github.workspace}}/third_party/llvm-project/build" && ninja

    - name: Configure CMake
      run: |
          mkdir build && cd build
          cmake -G Ninja ..  \
            -DLLVM_DIR=$PWD/../third_party/llvm-project/build/lib/cmake/llvm \
            -DMLIR_DIR=$PWD/../third_party/llvm-project/build/lib/cmake/mlir \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DSNNMLIR_ENABLE_BINDINGS_PYTHON=ON

    - name: Build
      run: cd build && ninja && ninja snn-opt

    - name: Test
      run: cd build && ninja check-snn-lit

