# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Action Build via External Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Python
      uses: actions/setup-python@v5

    - name: Install Ninja on Linux
      run: sudo apt-get install ninja-build
  
    - name: Install Python Packages
      run: |
          sudo pip3 install lit numpy
          sudo pip3 install pybind11

    - uses: actions/checkout@v4

    - name: Submodule Init
      run: git submodule init

    - name: Submodule Update
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: |
          mkdir build && cd build
          cmake -G Ninja ../third_party/llvm-project/llvm \
            -DCMAKE_BUILD_TYPE=Debug \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DLLVM_EXTERNAL_PROJECTS=snn-mlir \
            -DLLVM_EXTERNAL_SNN_MLIR_SOURCE_DIR=.. 

    - name: Build
      run: cd build && ninja

    - name: Test
      run: cd build && ninja check-snn-lit

